In [1]:
import numpy as np


arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5],
                [9,8,7]] )


print("Array is of type: ", type(arr))


print("No. of dimensions: ", arr.ndim)


print("Shape of array: ", arr.shape)


print("Size of array: ", arr.size)


print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (3, 3)
Size of array:  9
Array stores elements of type:  int64


In [4]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("Array is of type: ", type(arr3d))


print("No. of dimensions: ", arr3d.ndim)


print("Shape of array: ", arr3d.shape)


print("Size of array: ", arr3d.size)


print("Array stores elements of type: ", arr3d.dtype)

print(np.__version__)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  3
Shape of array:  (2, 2, 3)
Size of array:  12
Array stores elements of type:  int64
1.17.2


In [5]:
import numpy as np

a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)

d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
			"Array type is complex:\n", d)


e = np.random.random((2, 2))
print ("\nA random array:\n", e)


f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)


g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
										"0 and 5:\n", g)
arr = np.array([[1, 2, 3, 4],
				[5, 2, 4, 2],
				[1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.20276765 0.92216898]
 [0.0306282  0.38756599]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [6]:
import numpy as np


arr = np.array([[-1, 2, 0, 4],
				[4, -0.5, 6, 0],
				[2.6, 0, 7, 8],
				[3, -7, 4, 2.0]])


temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
					"columns(0 and 2):\n", temp)


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [18]:
###Arithmetic operations on numpy arrays
a=np.array([1,4,8])
b=np.array([7,0,3])
c=np.array([2,7+2j,0.4j])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.remainder(a,b))
print(np.reciprocal(a))
print(np.power(a,2))
print(np.power(a,b))
print(np.real(c))
print(np.imag(c))
print(np.conj(c))
print(np.sqrt(a))
print(np.min(a))
print(np.max(b))
print(np.mean(a))
print(np.max(a))
print(np.log(a))
print(np.sin(a))
print(np.sort(b))
print(np.append(a,2))
print(np.insert(b,2,5))
print(np.)

[ 8  4 11]
[-6  4  5]
[ 7  0 24]
[0.14285714        inf 2.66666667]
[1 0 2]
[1 0 2]
[1 0 0]
[ 1 16 64]
[  1   1 512]
[2. 7. 0.]
[0.  2.  0.4]
[2.-0.j  7.-2.j  0.-0.4j]
[1.         2.         2.82842712]
1
7
4.333333333333333
8
[0.         1.38629436 2.07944154]
[ 0.84147098 -0.7568025   0.98935825]
[0 3 7]
[1 4 8 2]
[7 0 5 3]


/Users/shwetakumari/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  
/Users/shwetakumari/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in remainder
  if __name__ == '__main__':
/Users/shwetakumari/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in remainder
  # Remove the CWD from sys.path while we load stuff.


In [19]:
import numpy as np

arr = np.array([[1, 5, 6],
				[4, 7, 2],
				[3, 1, 9]])

print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
					arr.max(axis = 1))


print ("Column-wise minimum elements:",
						arr.min(axis = 0))


print ("Sum of all array elements:",
							arr.sum())


print ("Cumulative sum along each row:\n",
						arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [20]:
import numpy as np


a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))


a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))


print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [21]:
import numpy as np

a = np.array([[1, 4, 2],
				[3, 4, 6],
			[0, -1, 5]])

print ("Array elements in sorted order:\n",
					np.sort(a, axis = None))


print ("Row-wise sorted array:\n",
				np.sort(a, axis = 1))


print ("Column wise sort by applying merge-sort:\n",
			np.sort(a, axis = 0, kind = 'mergesort'))


dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]


values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
		('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
			

arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
			np.sort(arr, order = 'name'))
			
print ("Array sorted by grauation year and then cgpa:\n",
				np.sort(arr, order = ['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
